### ISSUE TITLE
Question: JDO 3.2 API

### ISSUE THREAD

**Issue by stevespringett** [datanucleus/datanucleus-api-jdo#58]
I'm currently using Datanucleus 4.1 because it was the last major release that used a stable JDO release (3.1). All DN releases since have used JDO API 3.2 milestones.

My question is around the availability of the 3.2 spec so that a DN release can use a stable JDO spec. I'm wondering when 3.2 will realistically be out? This year, next year, etc? 

By looking at the Apache issue tracker for 3.2, it looks like its nearing completion, but it's hard to say since there really isn't any outbound communication from the group.

Anyway, I'm working on several projects that use JDO exclusively and I'm trying to roadmap my own projects with that of an eventual upgrade of DN with JDO 3.2. Any insight would be helpful.

**Comment by andyjefferson** [comment]
This isn't the place for a question of that nature (an issue tracker is for issues in the software). Ask the Apache JDO group themselves on their mailing list. 

From my personal POV, there is nothing else to be done other than add some more tests (and bearing in mind all changes in this release are ones that I pushed for), and update the spec, and fulfill whatever requirements the "JCP" have (not a body that I participate in, or believe in). The Apache JDO group don't put out releases of milestones like we do that is why we have our own mirror javax.jdo project that reflects their codebase, so we can release it. 

I see no reason why anyone would NOT use it, since the JDO 3.2 API is developed through the official group responsible for it. So what if it hasn't passed some "gate" in some Oracle body?
